### ISSUE TITLE
API

### ISSUE THREAD

**Issue by xinthose** [mishmanners/MishManners#1]
Hello.  So, apparently you cannot load `javascript` or `iframes` directly in the `README`?  Is there some sort of API I can reference?  Thank you.

**Comment by MishManners** [comment]
Hey great question @xinthose, let me get back to you on that.

**Comment by bdougie** [comment]
@xinthose this is not possible in the profile ReadME due to security reasons. However, Folks have been using SVGs as a workaround for this. 

see https://github.com/Platane/snk as an example of this.
