### ISSUE TITLE
Something got messed up in your most recent github.blog post

### ISSUE THREAD

**Issue by rmacklin** [mishmanners/MishManners#15]
Hi @mishmanners - something appears to have gotten messed up on https://github.blog/developer-skills/github/how-to-level-up-your-git-game-with-github-cli/

The list jumps from number 5 to number 8:

![image](https://github.com/user-attachments/assets/b9e1f2c7-ddd7-40c6-85e7-64f031acceb5)

though there is still a bit of text about `gh label` and `gh status` (which seems to have been intended for the missing numbers 6 and 7).

**Comment by rmacklin** [comment]
Looks like items 6 and 7 are available in this archive:

https://web.archive.org/web/20240816011628/https://github.blog/developer-skills/github/how-to-level-up-your-git-game-with-github-cli/

Looks like it broke sometime between 20240816032436 and 20240816194406

**Comment by rmacklin** [comment]
This appears to have now been fixed.

<img width="374" alt="image" src="https://github.com/user-attachments/assets/3ae985c2-0cd7-4510-bc93-376456c00207">

**Comment by mishmanners** [comment]
Yes thank you very much for all this! I managed to fix it all. Thank you again for putting it on my radar ❤ .
